// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY1SRUHSE1kSDONjCCUinosmyg_IEwS3o',
    appId: '1:671664167961:web:0a2bc7b69145467569de88',
    messagingSenderId: '671664167961',
    projectId: 'realtime-7b2e1',
    authDomain: 'realtime-7b2e1.firebaseapp.com',
    storageBucket: 'realtime-7b2e1.firebasestorage.app',
    measurementId: 'G-XWG7D58FNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxJDXGBv8vQDcYpfE2QibhUGVv2b9GUds',
    appId: '1:671664167961:android:3f658d841ffc21ec69de88',
    messagingSenderId: '671664167961',
    projectId: 'realtime-7b2e1',
    storageBucket: 'realtime-7b2e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiSNPE6EJKHxy-ITDXLfThHHlq_LWr_xE',
    appId: '1:671664167961:ios:75886b0b4c54d26769de88',
    messagingSenderId: '671664167961',
    projectId: 'realtime-7b2e1',
    storageBucket: 'realtime-7b2e1.firebasestorage.app',
    iosBundleId: 'com.example.realtime',
  );
}
